
CFLAGS := -I../inst/include -I/usr/local/boost -Wall -g -fPIC 
CXXFLAGS := $(CFLAGS)

LDFLAGS := -L../inst/lib -lvamp-sdk -L/usr/local/boost/stage/lib 
PLUGIN_LDFLAGS := -dynamiclib
PLUGIN_EXT := .dylib

include Makefile.inc

