
CFLAGS := -Wall -g -fPIC 
CXXFLAGS := $(CFLAGS)

PLUGIN_LDFLAGS := -shared -Wl,-Bstatic -lvamp-sdk -Wl,-Bdynamic -Wl,-Bsymbolic -Wl,-z,defs -Wl,--version-script=vamp-plugin.map

PLUGIN_EXT := .so

include Makefile.inc

